package main

import "fmt"

func Ecriture() {
	fmt.Printf("             _,._\n")
	fmt.Printf("           ,'   ,`-.\n")
	fmt.Printf("|.        /     |\\  `.\n")
	fmt.Printf("\\ \\      (  ,-,-` ). `-._ __ \n")
	fmt.Printf(" \\ \\      \\|\\,'     `\\  /'  `\\ \n")
	fmt.Printf("  \\ \\      ` |, ,  /  \\ \\     \\ \n")
	fmt.Printf("   \\ \\         `,_/`, /\\,`-.__/`.\n")
	fmt.Printf("    \\ \\            | ` /    /    `-._ \n")
	fmt.Printf("     \\\\           `-/'    /         `-. \n")
	fmt.Printf("      \\`/ _______,-/_   /'             \\ \n")
	fmt.Printf("     ---'`|       |`  ),' `---.  ,       | \n")
	fmt.Printf("       \\..-`--..___|_,/          /       / \n")
	fmt.Printf("                 |    |`,-,...,/      ,'  \n")
	fmt.Printf("                 \\    | |_|   /     ,' __  r-'', \n")
	fmt.Printf("                  |___|/  |, /  __ /-''  `'`)  | \n")
	fmt.Printf("               _,-'   ||__\\ /,-' /     _,.--|  ( \n")
	fmt.Printf("            .-'       )   `(_   / _,.-'  ,-' _,/ \n")
	fmt.Printf("             `-------'       `--''       `''' \n")

	fmt.Printf("             .--. \n")
	fmt.Printf("            /.--.\\ \n")
	fmt.Printf("            |====| \n")
	fmt.Printf("            |`::`| \n")
	fmt.Printf("        .-;`\\..../`;_.-^-._ \n")
	fmt.Printf(" /\\   /  |...::..|`   :   `| \n")
	fmt.Printf(" |:'\\ |   /'''::''|   .:.   | \n")
	fmt.Printf("@|\\ /\\;-,/\\   ::  |..:::::..| \n")
	fmt.Printf("`||\\ <` >  >._::_.| ':::::' | \n")
	fmt.Printf(" || ` `  /   ^^  |   ':'   | \n")
	fmt.Printf(" ||       |       \\    :    / \n")
	fmt.Printf(" ||       |        \\   :   /  \n")
	fmt.Printf(" ||       |___/\\___|`-.:.-` \n")
	fmt.Printf(" ||        \\_ || _/  \n")
	fmt.Printf(" ||        <_ >< _> \n")
	fmt.Printf(" ||        |  ||  | \n")
	fmt.Printf(" ||        |  ||  | \n")
	fmt.Printf(" ||       _\\.:||:./_ \n")
	fmt.Printf(" \\/     /____/\\____\\  \n")

	fmt.Printf("          _......._ \n")
	fmt.Printf("       .-'.'.'.'.'.'.`-. \n")
	fmt.Printf("     .'.'.'.'.'.'.'.'.'.`. \n")
	fmt.Printf("    /.'.'               '.\\ \n")
	fmt.Printf("     |.'    _.--...--._     | \n")
	fmt.Printf("    \\    `._.-.....-._.'   / \n")
	fmt.Printf("    |     _..- .-. -.._   | \n")
	fmt.Printf(" .-.'    `.   ((@))  .'   '.-. \n")
	fmt.Printf("( ^ \\      `--.   .-'     / ^ ) \n")
	fmt.Printf(" \\  /         .   .       \\  / \n")
	fmt.Printf("( _.\\    \\ (_`-._.-'_)    /._\\) \n")
	fmt.Printf(" `-' \\   ' .--.          / `-' \n")
	fmt.Printf("     |  / /|_| `-._.'\\   | \n")
	fmt.Printf("     |   |       |_| |   /-.._ \n")
	fmt.Printf(" _..-\\   `.--.______.'  | \n")
	fmt.Printf("      \\       .....     | \n")
	fmt.Printf("       `.  .'      `.  / \n")
	fmt.Printf("         \\           .' \n")
	fmt.Printf("          `-..___..-`  \n")

	fmt.Printf("                            ,-. \n")
	fmt.Printf("       ___,---.__          /'|`\\          __,---,___ \n")
	fmt.Printf("    ,-'    \\`    `-.____,-'  |  `-.____,-'    //    `-. \n")
	fmt.Printf("  ,'        |           ~'\\     /`~           |        `. \n")
	fmt.Printf(" /      ___//              `. ,'          ,  , \\___      \\ \n")
	fmt.Printf("|    ,-'   `-.__   _         |        ,    __,-'   `-.    | \n")
	fmt.Printf("|   /          /\\_  `   .    |    ,      _/\\          \\   | \n")
	fmt.Printf("\\  |           \\ \\`-.___ \\   |   / ___,-'/ /           |  / \n")
	fmt.Printf(" \\  \\           | `._   `\\  |  //'   _,' |           /  / \n")
	fmt.Printf("  `-.\\         /'  _ `---'' , . ``---' _  `\\         /,-' \n")
	fmt.Printf("     ``       /     \\    ,='/ \\`=.    /     \\       '' \n")
	fmt.Printf("             |__   /|\\_,--.,-.--,--._/|\\   __| \n")
	fmt.Printf("             /  `./  \\`\\ |  |  | /,//' \\,'  \\ \n")
	fmt.Printf("            /   /     ||--+--|--+-/-|     \\   \v \n")
	fmt.Printf("           |   |     /'\\_\\_\\ | /_/_/`\\     |   | \n")
	fmt.Printf("            \\   \\__, \\_     `~'     _/ .__/   / \n")
	fmt.Printf("             `-._,-'   `-._______,-'   `-._,-' \n")

	fmt.Printf("                                            __----~~~~~~~~~~~------___ \n")
	fmt.Printf("                                  .  .   ~~//====......          __--~ ~~ \n")
	fmt.Printf("                  -.            \\_|//     |||\\  ~~~~~~::::... /~ \n")
	fmt.Printf("               ___-==_       _-~o~  \\/    |||  \\            _/~~- \n")
	fmt.Printf("       __---~~~.==~||\\=_    -_--~/_-~|-   |\\   \\        _/~ \n")
	fmt.Printf("   _-~~     .=~    |  \\-_    '-~7  /-   /  ||    \\      / \n")
	fmt.Printf(" .~       .~       |   \\ -_    /  /-   /   ||      \\   / \n")
	fmt.Printf("/  ____  /         |     \\ ~-_/  /|- _/   .||       \\ / \n")
	fmt.Printf("|~~    ~~|--~~~~--_ \\     ~==-/   | \\~--===~~        .\\ \n")
	fmt.Printf("         '         ~-|      /|    |-~\\~~       __--~~ \n")
	fmt.Printf("                     |-~~-_/ |    |   ~\\_   _-~            /\\ \n")
	fmt.Printf("                          /  \\     \\__   \\/~                \\__ \n")
	fmt.Printf("                      _--~ _/ | .-~~____--~-/                  ~~==. \n")
	fmt.Printf("                     ((->/~   '.|||' -_|    ~~-/ ,              . _|| \n")
	fmt.Printf("                                -_     ~\\      ~~---l__i__i__i--~~_/ \n")
	fmt.Printf("                                _-~-__   ~)  \\--______________--~~ \n")
	fmt.Printf("                              //.-~~~-~_--~- |-------~~~~~~~~ \n")
	fmt.Printf("                                     //.-~~~--\\ \n")

	fmt.Printf("                 /| \n")
	fmt.Printf("  _______________)|..  \n")
	fmt.Printf("<'______________<(,_|)  \n")
	fmt.Printf("           .((()))| ))  \n")
	fmt.Printf("           (======)| \\  \n")
	fmt.Printf("          ((( o o ()|_ \\ \n")
	fmt.Printf("         '()))(_)/_/ ' ) \n")
	fmt.Printf("         .--/_\\ /(  /./ \n")
	fmt.Printf("        /'._.--\\ .-(_/   \n")
	fmt.Printf("       / / )\\___:___)  \n")
	fmt.Printf("      ( -.'.._  |  / \n")
	fmt.Printf("       \\  \\_\\ ( | ) \n")
	fmt.Printf("        '. /\\)_(_)| \n")
	fmt.Printf("          '-|  XX | \n")
	fmt.Printf("           %%%%%%%% \n")
	fmt.Printf("          / %%%%%%%\\ \n")
	fmt.Printf("         ( /.-'%%%. \\  \n")
	fmt.Printf("        /(.'   %%\\ :| \n")
	fmt.Printf("       / ,|    %  ) ) \n")
	fmt.Printf("     _|___)   %  (__|_ \n")
	fmt.Printf("     )___/       )___( \n")
	fmt.Printf("      |x/         \\ > \n")
	fmt.Printf("      |x)         / '. \n")
	fmt.Printf("      |x\\       _(____''.__ \n")
	fmt.Printf("    --\\ -\\-- \n")
	fmt.Printf("     --\\__|-- \n")

}
